@API_URL = http://localhost:1278/api

### GET VEHICLE BY LICENSE PLATE
GET {{API_URL}}/vehicles/CJH-462

### GET ALL VEHICLE BRANDS
GET {{API_URL}}/vehicles/brands

### GET VEHICLE MODELS BY BRAND ID
GET {{API_URL}}/vehicles/brands/1/models

### GET ALL VEHICLE MODELS
GET {{API_URL}}/vehicles/models

### GET ALL VEHICLE COLORS
GET {{API_URL}}/vehicles/colors

### GET ALL VEHICLE FUELS
GET {{API_URL}}/vehicles/fuels

### GET ALL PROVINCES
GET {{API_URL}}/localization/provinces

### GET ALL DISTRICTS BY PROVINCE
GET {{API_URL}}/localization/provinces/3/districts

### GET CLIENT SUMMARY
GET {{API_URL}}/clients

### GET DOCUMENT TYPES
GET {{API_URL}}/clients/documents/types

### GET FARES
GET {{API_URL}}/fares

### ADD VEHICLE BRAND
POST {{API_URL}}/vehicles/brands
Content-Type: application/json

{
    "name": "a "
}

### ADD VEHICLE MODEL
POST {{API_URL}}/vehicles/models
Content-Type: application/json

{
    "idBrand": 1,
    "name": "XD"
}

### GET NATURAL CLIENT BY ID
GET {{API_URL}}/clients/naturals/7

### GET ENTERPRISE CLIENT BY ID
GET {{API_URL}}/clients/enterprises

### ADD NATURAL CLIENT
POST {{API_URL}}/clients/naturals
Content-Type: application/json

{
    "idDocumentType": 1,
    "documentNumber": "20408612",
    "names": "Marlene Macedonia",
    "lastNames": "Ortiz Torres",
    "idProvince": 3,
    "idDistrict": 3,
    "address": "AA.HH 28 de mayo",
    "selfPhone": "914568919",
    "email": "marlene.macedonia@gmail.com",
    "idFare": 1
}

### ADD ENTERPRISE CLIENT
POST {{API_URL}}/clients/enterprises
Content-Type: application/json

{
    "idDocumentType": 2,
    "documentNumber": "20784512963",
    "companyName": "Washington Voces xd",
    "idProvince": 2,
    "idDistrict": 3,
    "address": "Av de la Constitución 100",
    "selfPhone": "951753959",
    "email": "wp_voces@gmail.com",
    "observations": "Es una empresa lol",
    "idFare": 1,
    "contactPerson": "Nill XD",
    "contactPhone": "951321032"
}

### ADD VEHICLE
POST {{API_URL}}/vehicles
Content-Type: application/json

{
    "licensePlate": "ABC340",
    "idBrand": 1,
    "idModel": 1,
    "idColor": 1,
    "year": 2020,
    "engineCapacity": 1000,
    "chassisNumber": "123456789",
    "idFuel": 1,
    "observations": "Este es un vehículo",
    "urlImage": "https://www.google.com/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png",
    "idPerson": 2
}

### GET RECEPTIONS
GET {{API_URL}}/receptions

### ADD RECEPTION
POST {{API_URL}}/receptions
Content-Type: application/json

{
    "date": "2021-01-01 00:00:00",
    "idVehicle": 8,
    "kilometers": 100,
    "towedIn": true,
    "idEmployee": 1,
    "promisedDate": "2021-01-01 00:00:00",
    "nonOwnerPerson": "Marlene Macedonia",
    "nonOwnerPhone": "914568919",
    "stateImageUrl": "https://www.google.com/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png",
    "repairNotes": "Este es un vehículo",
    "soatExpirationDate": "2021-01-01",
    "nextServiceDate": "2021-01-01",
    "inspectionExpirationDate": "2021-01-01"
}